### ISSUE TITLE
Versioning for the opensplice osrf fork

### ISSUE THREAD

**Issue by j-rivero** [osrf/opensplice#14]
Currently we are using the `release number` in versioning for naming the OSRF patchset version on top of upstream version (i.e. 6.4.0-0 version means OSRF patchset 0 on top of 6.4.0 upstream).

For packaging proposes I would need to have a proper `release number` to indicate changes in packaging metadata that do not affect source code. We can migrate the schema to something like:
 `${upstream-version}+osrf${osrf_patch_version}-${release_version}`

Current `6.4.0-0` (we will leave as it is now) would have been `6.4.0+osrf0-0` and next `6.4.0-1` will be `6.4.0+osrf1-0`. Note that apt will be able to upgrade from 6.4.0-0 to 6.4.0+osrf1-0 (test with: `dpkg --compare-versions 6.4.0-0 lt 6.4.0+osrf1-0 && echo "yes"`) so no migration needed if we change the schema to this proposal.

//cc @wjwwood @dirk-thomas

**Comment by dirk-thomas** [comment]
Sounds good to me.

**Comment by wjwwood** [comment]
+1 thanks @j-rivero
